### ISSUE TITLE
请问这种格式的数据如何做三级联查

### ISSUE THREAD

**Issue by Kumhy** [coderbusy/china-area#1]
例如页面加载完毕第一个section填充所有省，选择一个省后加载该省的所有地级数据。
行政区划代码不是唯一的，各级别之间的关联关系不大，不知道字幕处理这些数据，能告知下处理方法吗？

**Comment by Soar360** [comment]
你可以直接按照官网的方式进行筛选，传入三个级别的全部信息。或者购买我整理好的数据：
https://item.taobao.com/item.htm?id=556441596339
